#spring.config.activate.on-profile
spring:
  config:
    activate:
      on-profiles:
        active: dev
---
spring:
  profiles: dev
  data.mongodb:
    host: localhost
    port: 27017
    database: local
---
spring:
  profiles: nonprod
  data.mongodb:
    host: localhost
    port: 27017
    database: local
---
spring:
  profiles: prod
  data.mongodb:
    host: localhost
    port: 27017
    database: local
---
spring:
  profiles: test